class Global {
  static bool isIOS = false;

  static List<Map> foryouapps1 = [
    {
      'id': '1',
      'image': "assets/images/amazon.jpg",
      'name': 'Amazon',
      'description': 'Amazon Mobile LLC',
      'rate': '4.2',
    },
    {
      'id': '2',
      'image': "assets/images/appstore.jpg",
      'name': 'App Store',
      'description': 'Apple',
      'rate': '7.8',
    },
    {
      'id': '3',
      'image': "assets/images/git.png",
      'name': 'Git for Window',
      'description': 'GitHub',
      'rate': '9.5',
    },
    {
      'id': '4',
      'image': "assets/images/insta.jpg",
      'name': 'Instagram',
      'description': 'Instagram',
      'rate': '9.9',
    },
    {
      'id': '5',
      'image': "assets/images/meet.png",
      'name': 'Google meet',
      'description': 'Google LLC',
      'rate': '4.2',
    },
    {
      'id': '6',
      'image': "assets/images/message.jpg",
      'name': 'Messenger',
      'description': 'Meta Platform, inc.',
      'rate': '8.6',
    },
    {
      'id': '7',
      'image': "assets/images/phone.jpg",
      'name': 'Contacts',
      'description': 'Google LLC',
      'rate': '6.8',
    },
    {
      'id': '8',
      'image': "assets/images/picsart.jpg",
      'name': 'Picsart',
      'description': 'PicsArt, inc.',
      'rate': '8.6',
    },
    {
      'id': '9',
      'image': "assets/images/pizzahut.png",
      'name': 'Pizza Hut',
      'description': 'Piza hut digital',
      'rate': '7.6',
    },
    {
      'id': '10',
      'image': "assets/images/snap.png",
      'name': 'Snapchat',
      'description': 'Snap inc',
      'rate': '9.5',
    },
    {
      'id': '11',
      'image': "assets/images/spotify.png",
      'name': 'Spotify',
      'description': 'Spotify AB',
      'rate': '8.9',
    },
    {
      'id': '12',
      'image': "assets/images/telegram.png",
      'name': 'Telegram',
      'description': 'Telegram FZ-LLC',
      'rate': '9.2',
    },
    {
      'id': '13',
      'image': "assets/images/whatsapp.png",
      'name': 'Whatsapp',
      'description': 'Whatsapp LLC',
      'rate': '10.0',
    },
    {
      'id': '14',
      'image': "assets/images/zoom.png",
      'name': 'Zoom',
      'description': 'Google LLC',
      'rate': '9.2',
    },
  ];
  static List<Map> foryouapps2 = [
    {
      'id': '5',
      'image': "assets/images/meet.png",
      'name': 'Google meet',
      'description': 'Google LLC',
      'rate': '4.2',
    },
    {
      'id': '6',
      'image': "assets/images/message.jpg",
      'name': 'Messenger',
      'description': 'Meta Platform, inc.',
      'rate': '8.6',
    },
    {
      'id': '7',
      'image': "assets/images/phone.jpg",
      'name': 'Contacts',
      'description': 'Google LLC',
      'rate': '6.8',
    },
    {
      'id': '8',
      'image': "assets/images/picsart.jpg",
      'name': 'Picsart',
      'description': 'PicsArt, inc.',
      'rate': '8.6',
    },
    {
      'id': '9',
      'image': "assets/images/pizzahut.png",
      'name': 'Pizza Hut',
      'description': 'Piza hut digital',
      'rate': '7.6',
    },
    {
      'id': '10',
      'image': "assets/images/snap.png",
      'name': 'Snapchat',
      'description': 'Snap inc',
      'rate': '9.5',
    },
    {
      'id': '11',
      'image': "assets/images/spotify.png",
      'name': 'Spotify',
      'description': 'Spotify AB',
      'rate': '8.9',
    },
    {
      'id': '12',
      'image': "assets/images/telegram.png",
      'name': 'Telegram',
      'description': 'Telegram FZ-LLC',
      'rate': '9.2',
    },
    {
      'id': '13',
      'image': "assets/images/whatsapp.png",
      'name': 'Whatsapp',
      'description': 'Whatsapp LLC',
      'rate': '10.0',
    },
    {
      'id': '14',
      'image': "assets/images/zoom.png",
      'name': 'Zoom',
      'description': 'Google LLC',
      'rate': '9.2',
    },
  ];
  static List<Map> foryouapps3 = [
    {
      'id': '8',
      'image': "assets/images/picsart.jpg",
      'name': 'Picsart',
      'description': 'PicsArt, inc.',
      'rate': '8.6',
    },
    {
      'id': '9',
      'image': "assets/images/pizzahut.png",
      'name': 'Pizza Hut',
      'description': 'Piza hut digital',
      'rate': '7.6',
    },
    {
      'id': '10',
      'image': "assets/images/snap.png",
      'name': 'Snapchat',
      'description': 'Snap inc',
      'rate': '9.5',
    },
    {
      'id': '11',
      'image': "assets/images/spotify.png",
      'name': 'Spotify',
      'description': 'Spotify AB',
      'rate': '8.9',
    },
    {
      'id': '12',
      'image': "assets/images/telegram.png",
      'name': 'Telegram',
      'description': 'Telegram FZ-LLC',
      'rate': '9.2',
    },
    {
      'id': '13',
      'image': "assets/images/whatsapp.png",
      'name': 'Whatsapp',
      'description': 'Whatsapp LLC',
      'rate': '10.0',
    },
    {
      'id': '14',
      'image': "assets/images/zoom.png",
      'name': 'Zoom',
      'description': 'Google LLC',
      'rate': '9.2',
    },
  ];
  static List<Map> games = [
    {
      'id': '1',
      'image': "assets/images/games/pubg.jpg",
      'name': 'Pubg',
      'description': 'Tencent Games',
      'rate': '8.6',
    },
    {
      'id': '2',
      'image': "assets/images/games/patti.jpg",
      'name': 'Teen patti',
      'description': 'Octro',
      'rate': '7.6',
    },
    {
      'id': '3',
      'image': "assets/images/games/angry2.jpg",
      'name': 'Angry birds',
      'description': 'Rovio',
      'rate': '9.5',
    },
    {
      'id': '4',
      'image': "assets/images/games/asphalt.jpg",
      'name': 'Asphalt 9',
      'description': 'Gamelofy SE',
      'rate': '8.9',
    },
    {
      'id': '5',
      'image': "assets/images/games/freefire.jpg",
      'name': 'Garena free fire',
      'description': 'Garena international',
      'rate': '9.2',
    },
    {
      'id': '6',
      'image': "assets/images/games/ludo.jpg",
      'name': 'Ludo',
      'description': 'Board',
      'rate': '10.0',
    },
    {
      'id': '7',
      'image': "assets/images/games/rider.jpg",
      'name': 'Rider',
      'description': 'Strome Gamer',
      'rate': '9.2',
    },
    {
      'id': '8',
      'image': "assets/images/games/subway.jpg",
      'name': 'Subway Surfers',
      'description': 'SYBO Studios',
      'rate': '9.2',
    },
    {
      'id': '9',
      'image': "assets/images/games/tempalrun.jpg",
      'name': 'Tempal Run',
      'description': 'imangi Studios',
      'rate': '9.2',
    },
  ];
}
